// <auto-generated />
using System;
using CapstoneRegistration.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CapstoneRegistration.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260416211846_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CapstoneRegistration.API.Models.CapstoneProject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Abbreviation")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("abbreviation");

                    b.Property<string>("ClassName")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("class");

                    b.Property<string>("Context")
                        .HasColumnType("text")
                        .HasColumnName("context");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id");

                    b.Property<DateOnly?>("DurationFrom")
                        .HasColumnType("date")
                        .HasColumnName("duration_from");

                    b.Property<DateOnly?>("DurationTo")
                        .HasColumnType("date")
                        .HasColumnName("duration_to");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("english_name");

                    b.Property<string>("FunctionalRequirements")
                        .HasColumnType("text")
                        .HasColumnName("functional_requirements");

                    b.Property<bool>("IsEnterpriseProject")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enterprise_project");

                    b.Property<bool>("IsResearchProject")
                        .HasColumnType("boolean")
                        .HasColumnName("is_research_project");

                    b.Property<string>("NonFunctionalRequirements")
                        .HasColumnType("text")
                        .HasColumnName("non_functional_requirements");

                    b.Property<string>("Products")
                        .HasColumnType("text")
                        .HasColumnName("products");

                    b.Property<string>("Profession")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("profession");

                    b.Property<string>("ProjectCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("project_code");

                    b.Property<string>("ProposedSolutions")
                        .HasColumnType("text")
                        .HasColumnName("proposed_solutions");

                    b.Property<string>("ProposedTasks")
                        .HasColumnType("text")
                        .HasColumnName("proposed_tasks");

                    b.Property<string>("RegisterKind")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("register_kind");

                    b.Property<string>("SemesterId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("semester_id");

                    b.Property<string>("Specialty")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("specialty");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("TheoryAndPractice")
                        .HasColumnType("text")
                        .HasColumnName("theory_and_practice");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("VietnameseName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("vietnamese_name");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ProjectCode")
                        .IsUnique()
                        .HasDatabaseName("idx_capstone_projects_project_code");

                    b.HasIndex("SemesterId")
                        .HasDatabaseName("idx_capstone_projects_semester_id");

                    b.ToTable("capstone_projects");
                });

            modelBuilder.Entity("CapstoneRegistration.API.Models.ProjectReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("decision");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<DateTime>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<Guid>("ReviewedById")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewed_by_id");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("idx_project_reviews_project_id");

                    b.HasIndex("ReviewedById")
                        .HasDatabaseName("idx_project_reviews_reviewed_by_id");

                    b.ToTable("project_reviews");
                });

            modelBuilder.Entity("CapstoneRegistration.API.Models.ProjectStudent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("full_name");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("RoleInGroup")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("role_in_group");

                    b.Property<string>("StudentCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("student_code");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("project_students");
                });

            modelBuilder.Entity("CapstoneRegistration.API.Models.ProjectSupervisor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("project_supervisors");
                });

            modelBuilder.Entity("CapstoneRegistration.API.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("avatar_url");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_email_verified");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("idx_users_email");

                    b.ToTable("users");
                });

            modelBuilder.Entity("CapstoneRegistration.API.Models.CapstoneProject", b =>
                {
                    b.HasOne("CapstoneRegistration.API.Models.User", "CreatedBy")
                        .WithMany("CreatedProjects")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("CapstoneRegistration.API.Models.ProjectReview", b =>
                {
                    b.HasOne("CapstoneRegistration.API.Models.CapstoneProject", "Project")
                        .WithMany("ProjectReviews")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CapstoneRegistration.API.Models.User", "ReviewedBy")
                        .WithMany("Reviews")
                        .HasForeignKey("ReviewedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("ReviewedBy");
                });

            modelBuilder.Entity("CapstoneRegistration.API.Models.ProjectStudent", b =>
                {
                    b.HasOne("CapstoneRegistration.API.Models.CapstoneProject", "Project")
                        .WithMany("Students")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("CapstoneRegistration.API.Models.ProjectSupervisor", b =>
                {
                    b.HasOne("CapstoneRegistration.API.Models.CapstoneProject", "Project")
                        .WithMany("Supervisors")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("CapstoneRegistration.API.Models.CapstoneProject", b =>
                {
                    b.Navigation("ProjectReviews");

                    b.Navigation("Students");

                    b.Navigation("Supervisors");
                });

            modelBuilder.Entity("CapstoneRegistration.API.Models.User", b =>
                {
                    b.Navigation("CreatedProjects");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
